import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import FloatingActions from "@/components/common/FloatingActions";
import ThemeWrapper from "@/components/ThemeWrapper";
import PageTransition from "@/components/common/PageTransition";

const sfReg = localFont({
  src: "../../public/assets/fonts/SF-Pro-Display-Regular.otf",
  variable: "--font-sfReg"
});

const sfBlack = localFont({
  src: "../../public/assets/fonts/SF-Pro-Display-Black.otf",
  variable: "--font-sfBlack",
})


const sfBold = localFont({
  src: "../../public/assets/fonts/SF-Pro-Display-Bold.otf",
  variable: "--font-sfBold"
})

const ppMontreal = localFont({
  src: "../../public/assets/fonts/ppneuemontreal-medium.otf",
  variable: "--font-ppMontreal"
})

export const metadata: Metadata = {
  title: "KEEP-UP",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sfReg.variable} ${sfBold.variable} ${sfBlack.variable} ${ppMontreal.variable} antialiased`}
      >
        <PageTransition>
        <StoreProvider>
          <ThemeWrapper>
            {children}
            <FloatingActions />
          </ThemeWrapper>
        </StoreProvider>
        </PageTransition>
      </body>
    </html>
  );
}
