// ============================================================================
// ONBOARDING TYPES
// ============================================================================

/**
 * Occupation details for user profile
 */
export interface OccupationDetails {
    hours_per_week: number;
    schedule_type: string;
    is_sedentary: boolean;
}

/**
 * Weekly schedule structure in the final plan
 */
export interface WeeklySchedule {
    week: number;
    workouts_per_week: number;
    focus: string;
}

/**
 * Agent information in the debate
 */
export interface DebateAgent {
    agent: string;
    role: string;
    proposal?: {
        interpreted_goal: string;
        weekly_target: string;
        first_milestone: string;
        reasoning: string;
    };
    analysis?: {
        identified_patterns?: string[];
        quit_probability?: number;
        plan_concerns?: string[];
    };
    challenge?: {
        stance: string | null;
        reasoning: string | null;
        counter_proposal: string | null;
    };
}

/**
 * Complete debate data structure
 */
export interface DebateSummary {
    agents?: DebateAgent[];
    synthesis?: string;
    safety_adjustments?: string[];
}

/**
 * Final plan generated by the AI council
 */
export interface FinalPlan {
    interpreted_goal: string;
    weekly_target: string;
    first_milestone: string;
    timeline_weeks?: number;
    weekly_schedule?: WeeklySchedule[];
    safety_notes?: string[];
}

/**
 * Core domains for the resolution
 */
export type GoalDomain = 'physical' | 'mental' | 'emotional' | 'lifestyle';

/**
 * Onboarding form data submitted to the API
 */
export interface OnboardingData {
    domain?: GoalDomain;
    resolution_text: string;
    past_attempts?: string;
    life_constraints?: string[];
    occupation?: string;
    occupation_details?: OccupationDetails;
}

/**
 * Response from the onboarding API
 */
export interface OnboardingResponse {
    debate_summary: DebateSummary;
    final_plan: FinalPlan;
    confidence_score: number;
}
