from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Text, Boolean
from sqlalchemy.orm import relationship
from datetime import datetime
from core.database import Base


class AgentRecommendation(Base):
    """
    AI agent's recommendation for user based on daily check-in data.
    Generated by agents analyzing sleep, stress, biometrics, nutrition.
    Includes reasoning and confidence score.
    """
    __tablename__ = "agent_recommendation"

    id = Column(Integer, primary_key=True, index=True)
    resolution_id = Column(Integer, ForeignKey("resolutions.id", ondelete="CASCADE"), nullable=False, index=True)
    daily_checkin_id = Column(Integer, ForeignKey("daily_checkin.id", ondelete="CASCADE"), nullable=True, index=True)
    
    # The recommendation itself
    recommendation_type = Column(String(100), nullable=False)  # "skip_workout", "reduce_intensity", "recovery_focus", "normal", "push_harder"
    recommendation_text = Column(Text, nullable=False)
    
    # Why this recommendation?
    reasoning = Column(Text, nullable=False)  # Explanation of the decision
    
    # Which agent made this?
    agent_name = Column(String(100), nullable=False)  # e.g., "emotional_agent", "task_management_agent"
    agent_type = Column(String(100), nullable=True)  # "primary", "secondary", "ensemble"
    
    # Confidence and metrics
    confidence_score = Column(Float, nullable=False, default=0.5)  # 0.0-1.0
    supporting_factors = Column(Text, nullable=True)  # e.g., "high_stress, low_sleep, dehydration"
    
    # Opik integration
    opik_trace_id = Column(String(255), nullable=True)  # Link to Opik trace for full reasoning chain
    
    # Workout plan (if applicable)
    recommended_workout_type = Column(String(100), nullable=True)  # "strength", "cardio", "mobility", "rest"
    recommended_duration_minutes = Column(Integer, nullable=True)
    recommended_intensity = Column(String(50), nullable=True)  # "light", "moderate", "high"
    
    # User interaction
    user_accepted = Column(Boolean, default=None, nullable=True)
    user_feedback = Column(Text, nullable=True)
    
    # Outcome tracking
    outcome_notes = Column(Text, nullable=True)  # Did user follow? How did it go?
    effectiveness_rating = Column(Integer, nullable=True)  # 1-10: user's rating of recommendation
    
    # Metadata
    date = Column(DateTime, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    resolution = relationship("Resolution", back_populates="agent_recommendations")
    daily_checkin = relationship("DailyCheckIn", back_populates="agent_recommendations")
